export const agentData = [
  {
    id: 1,
    country: 'United States',
    shortCountry: 'USA',
    name: '5 Alarm Music',
    address1: '35 West Dayton St.',
    address2: '',
    address3: 'Pasadena, CA 91105',
    agentName: 'Cassie Lord',
    phone: '(626) 304-1698',
    fax: '(626) 795-2058',
    email: 'cassie@5alarmmusic.com',
    url: 'http://5alarmmusic.com/',
    urlDisplay: '5alarmmusic.com',
    sonicUrl: 'http://5alarmmusic.com/music/sonic-quiver/',
  },
  {
    id: 2,
    country: 'Austria',
    shortCountry: 'Austria',
    name: 'Musikverlag G. Narholz',
    address1: 'Inh. G. Diaz',
    address2: 'Harstubenweg 13',
    address3: '4813 Altmünster, Austria',
    agentName: 'Rotheide Narholz',
    phone: '43-7612-87029',
    fax: '43-7612-88791',
    email: 'verlag@sonoton.com',
    url: 'https://www.sonoton.com/',
    urlDisplay: 'www.sonoton.com',
    sonicUrl: 'https://www.sonoton.com/',
  },
  {
    id: 3,
    country: 'Belgium',
    shortCountry: 'Belgium',
    name: 'Music & Images',
    address1: 'Rogierlaan 297',
    address2: '1030 Brussels',
    address3: 'Belgium',
    agentName: 'Annemie Hendrikx',
    phone: '+32 22 456 123',
    fax: '',
    email: 'info@musicandimages.be',
    url: 'http://musicandimages.be/',
    urlDisplay: 'musicandimages.be',
    sonicUrl: 'http://musicandimages.be/',
  },
  {
    id: 4,
    country: 'Czech Republic',
    shortCountry: 'Czech Republic',
    name: 'Studio Fontana spol. s r.o.',
    address1: 'V PodvrÅ¡Ã­ 1',
    address2: '182 00 Praha 8',
    address3: 'Czech Republic',
    agentName: 'ZdenÄ›k NedvÄ›d',
    phone: '+420 266 711 432-33',
    fax: '+420 266 711 432-33',
    email: 'library@studiofontana.com',
    url: 'http://www.studiofontana.com/',
    urlDisplay: 'www.studiofontana.com',
    sonicUrl: 'http://musicandimages.be/',
  },
  {
    id: 5,
    country: 'Finland',
    shortCountry: 'Finland',
    name: 'Upright Music Scandinavia',
    address1: 'Vesterbrogade 74, 4',
    address2: 'DK-1620 Copenhagen',
    address3: 'Denmark',
    agentName: 'Jeppe Kaltoft',
    phone: '(+45) 70 26 14 00',
    fax: '',
    email: 'jk@upright-music.com',
    url: 'https://www.upright-music.com/',
    urlDisplay: 'www.upright-music.com',
    sonicUrl: 'https://search.upright-music.com/search/nojs?phrase[1]=sonic%20quiver',
  },
  {
    id: 6,
    country: 'Germany',
    shortCountry: 'Germany',
    name: 'Sonoton Music GmbH & Co. KG',
    address1: 'Schleibingerstr. 10',
    address2: 'Munchen, 81699',
    address3: 'Germany',
    agentName: 'Heidi Narholz',
    phone: '49(0)89/44 77 82-0',
    fax: '49(0)89/44 77 82-88',
    email: 'sonoton@sonoton.com',
    url: 'https://www.sonoton.de/',
    urlDisplay: 'www.sonoton.de',
    sonicUrl: 'https://search.upright-music.com/search/nojs?phrase[1]=sonic%20quiver',
  },
]
