export const agentData = [
  {
    id: 1,
    country: 'United States',
    shortCountry: 'USA',
    sortString: 'AAAA',
    name: '5 Alarm Music',
    address1: '35 West Dayton St.',
    address2: '',
    address3: 'Pasadena, CA 91105',
    agentName: 'Cassie Lord',
    phone: '(626) 304-1698',
    fax: '(626) 795-2058',
    email: 'cassie@5alarmmusic.com',
    url: 'http://5alarmmusic.com/',
    urlDisplay: '5alarmmusic.com',
    sonicUrl: 'http://5alarmmusic.com/music/sonic-quiver/',
  },
  {
    id: 2,
    country: 'Austria',
    shortCountry: 'Austria',
    sortString: 'Austria',
    name: 'Musikverlag G. Narholz',
    address1: 'Inh. G. Diaz',
    address2: 'Harstubenweg 13',
    address3: '4813 Altmünster, Austria',
    agentName: 'Rotheide Narholz',
    phone: '43-7612-87029',
    fax: '43-7612-88791',
    email: 'verlag@sonoton.com',
    url: 'https://www.sonoton.com/',
    urlDisplay: 'www.sonoton.com',
    sonicUrl: 'https://www.sonoton.com/',
  },
  {
    id: 3,
    country: 'Belgium',
    shortCountry: 'Belgium',
    sortString: 'Belgium',
    name: 'Music & Images',
    address1: 'Rogierlaan 297',
    address2: '1030 Brussels',
    address3: 'Belgium',
    agentName: 'Annemie Hendrikx',
    phone: '+32 22 456 123',
    fax: '',
    email: 'info@musicandimages.be',
    url: 'http://musicandimages.be/',
    urlDisplay: 'musicandimages.be',
    sonicUrl: 'http://musicandimages.be/',
  },
  {
    id: 4,
    country: 'Czech Republic',
    shortCountry: 'Czech Republic',
    sortString: 'Czech Republic',
    name: 'Studio Fontana spol. s r.o.',
    address1: 'V PodvrÅ¡Ã­ 1',
    address2: '182 00 Praha 8',
    address3: 'Czech Republic',
    agentName: 'ZdenÄ›k NedvÄ›d',
    phone: '+420 266 711 432-33',
    fax: '+420 266 711 432-33',
    email: 'library@studiofontana.com',
    url: 'http://www.studiofontana.com/',
    urlDisplay: 'www.studiofontana.com',
    sonicUrl: 'http://musicandimages.be/',
  },
  {
    id: 5,
    country: 'Finland',
    shortCountry: 'Finland',
    sortString: 'Finland',
    name: 'Upright Music Scandinavia',
    address1: 'Vesterbrogade 74, 4',
    address2: 'DK-1620 Copenhagen',
    address3: 'Denmark',
    agentName: 'Jeppe Kaltoft',
    phone: '(+45) 70 26 14 00',
    fax: '',
    email: 'jk@upright-music.com',
    url: 'https://www.upright-music.com/',
    urlDisplay: 'www.upright-music.com',
    sonicUrl: 'https://search.upright-music.com/search/nojs?phrase[1]=sonic%20quiver',
  },
  {
    id: 6,
    country: 'Germany',
    shortCountry: 'Germany',
    sortString: 'Germany',
    name: 'Sonoton Music GmbH & Co. KG',
    address1: 'Schleibingerstr. 10',
    address2: 'Munchen, 81699',
    address3: 'Germany',
    agentName: 'Heidi Narholz',
    phone: '49(0)89/44 77 82-0',
    fax: '49(0)89/44 77 82-88',
    email: 'sonoton@sonoton.com',
    url: 'https://www.sonoton.de/',
    urlDisplay: 'www.sonoton.de',
    sonicUrl: 'https://search.upright-music.com/search/nojs?phrase[1]=sonic%20quiver',
  },
  {
    id: 7,
    country: 'Hong Kong',
    shortCountry: 'Hong Kong',
    sortString: 'Hong Kong',
    name: 'Echo Music',
    address1: 'F 1, No. 10-1, Ln 107, Sec. 2,',
    address2: 'He Ping East Road, Taipei 106',
    address3: 'Taiwan R.O.C.',
    agentName: 'Robert Y Li',
    phone: '+886 (0)2 27071170',
    fax: '+886 (0)2 27071171',
    email: 'robert@echomusic.com',
    url: 'https://www.echomusicpg.com/',
    urlDisplay: 'www.echomusicpg.com',
    sonicUrl: 'http://www.echomusicpg.com/',
  },
  {
    id: 8,
    country: 'India & SAARC Countries',
    shortCountry: 'India & SAARC Countries',
    sortString: 'India',
    name: 'Big Bang & Fuzz',
    address1: 'Suite 902 / 2-14 Kings Cross Road',
    address2: 'Potts Point NSW 2011',
    address3: 'Australia',
    agentName: 'Andrew Jones',
    phone: '+61 2 9326 9122',
    fax: '+61 2 9326 9166',
    email: 'music@bigbangfuzz.com',
    url: 'https://www.bigbangfuzz.com/',
    urlDisplay: 'www.bigbangfuzz.com',
    sonicUrl: 'https://www.bigbangfuzz.com/#/label/07f5949bd17cf38b',
  },
  {
    id: 9,
    country: 'Israel',
    shortCountry: 'Israel',
    sortString: 'Israel',
    name: 'Karma Music Consulting',
    address1: 'Petach-Tiqwa',
    address2: 'Israel 49379',
    address3: '',
    agentName: 'Aviv Azerad',
    phone: '972-3-9210744',
    fax: '',
    email: 'aviv@karma-mc.com',
    url: 'https://www.karma-mc.com/',
    urlDisplay: 'www.karma-mc.com',
    sonicUrl: 'http://www.karma-mc.com/',
  },
  {
    id: 10,
    country: 'Japan',
    shortCountry: 'Japan',
    sortString: 'Japan',
    name: 'Nichion, Inc./Nichion Sounds Library',
    address1: 'Kokusai Shin-Akasaka Bldg., East Tower 12F 2-14-27',
    address2: 'Akasaka, Minato-ku',
    address3: 'Tokyo, 107-8380 Japan',
    agentName: 'Haruka Sato',
    phone: '81-3-5562-3888',
    fax: '81-3-5562-5405',
    email: 'jaruka_sato@nichion.co.jp',
    url: 'http://www.nichion.co.jp/',
    urlDisplay: 'www.ichion.co.jp',
    sonicUrl: 'http://www.nichion.co.jp/',
  },
  {
    id: 11,
    country: 'Mainland China',
    shortCountry: 'Mainland China',
    sortString: 'Mainland China',
    name: 'Echo Music',
    address1: 'F 1, No. 10-1, Ln 107, Sec. 2,',
    address2: 'He Ping East Road, Taipei 106',
    address3: 'Taiwan R.O.C.',
    agentName: 'Robert Y Li',
    phone: '+886 (0)2 27071170',
    fax: '+886 (0)2 27071171',
    email: 'robert@echomusic.com',
    url: 'https://www.echomusicpg.com/',
    urlDisplay: 'www.echomusicpg.com',
    sonicUrl: 'http://www.echomusicpg.com/',
  },
  {
    id: 12,
    country: 'Mexico',
    shortCountry: 'Mexico',
    sortString: 'Mexico',
    name: 'Music and Images, S.A. de C.V.',
    address1: 'Orizaba 101, Casa 1',
    address2: 'Col. Roma',
    address3: '06700 Mexico, D.F.',
    agentName: 'Peter Van Es',
    phone: '01 800 111-5050',
    fax: '',
    email: 'info@music-images.com',
    url: 'https://www.musicdirectorla.com/',
    urlDisplay: 'www.MusicDirectorLA.com',
    sonicUrl: 'https://www.musicdirectorla.com/labels/2681?sort=newest',
  },
  {
    id: 13,
    country: 'New Zealand',
    shortCountry: 'New Zealand',
    sortString: 'New Zealand',
    name: 'Big Bang & Fuzz',
    address1: 'Suite 902 / 2-14 Kings Cross Road',
    address2: 'Potts Point NSW 2011',
    address3: 'Australia',
    agentName: 'Andrew Jones',
    phone: '+61 2 9326 9122',
    fax: '+61 2 9326 9166',
    email: 'music@bigbangfuzz.com',
    url: 'https://www.bigbangfuzz.com/',
    urlDisplay: 'www.bigbangfuzz.com',
    sonicUrl: 'https://www.bigbangfuzz.com/#/label/07f5949bd17cf38b',
  },
  {
    id: 14,
    country: 'Poland',
    shortCountry: 'Poland',
    sortString: 'Poland',
    name: 'Apollo Music Sp. z o.o.',
    address1: 'ul. Bruzdowa 102a/3',
    address2: '02-991 Warszawa',
    address3: 'Poland',
    agentName: 'Rafal Salamon',
    phone: '48 22 619 67 80',
    fax: '48 22 619 67 80',
    email: 'rafal@apollomusic.pl',
    url: 'http://www.apollomusic.pl/',
    urlDisplay: 'www.apollomusic.pl',
    sonicUrl: 'http://www.apollomusic.pl/',
  },
  {
    id: 15,
    country: 'Republic of China',
    shortCountry: 'Republic of China',
    sortString: 'Republic of China',
    name: 'Echo Music',
    address1: 'F 1, No. 10-1, Ln 107, Sec. 2,',
    address2: 'He Ping East Road, Taipei 106',
    address3: 'Taiwan R.O.C.',
    agentName: 'Robert Y Li',
    phone: '+886 (0)2 27071170',
    fax: '+886 (0)2 27071171',
    email: 'robert@echomusic.com',
    url: 'https://www.echomusicpg.com/',
    urlDisplay: 'www.echomusicpg.com',
    sonicUrl: 'http://www.echomusicpg.com/',
  },
  {
    id: 16,
    country: 'Singapore',
    shortCountry: 'Singapore',
    sortString: 'Singapore',
    name: 'Big Bang & Fuzz',
    address1: 'Suite 902 / 2-14 Kings Cross Road',
    address2: 'Potts Point NSW 2011',
    address3: 'Australia',
    agentName: 'Andrew Jones',
    phone: '+61 2 9326 9122',
    fax: '+61 2 9326 9166',
    email: 'music@bigbangfuzz.com',
    url: 'https://www.bigbangfuzz.com/',
    urlDisplay: 'www.bigbangfuzz.com',
    sonicUrl: 'https://www.bigbangfuzz.com/#/label/07f5949bd17cf38b',
  },
  {
    id: 17,
    country: 'South Africa',
    shortCountry: 'South Africa',
    sortString: 'South Africa',
    name: 'Synchro Music Management',
    address1: 'PO Box 880',
    address2: 'Strubensvalley 1735',
    address3: 'Gauteng, South Africa',
    agentName: 'Louise Bulley',
    phone: '011-431 3827',
    fax: '086 607-8222',
    email: 'louise@synchromusic.biz',
    url: 'http://synchromusic.co.za/',
    urlDisplay: 'synchromusic.co.za',
    sonicUrl: 'http://synchromusic.co.za/',
  },
  {
    id: 18,
    country: 'Spain',
    shortCountry: 'Spain',
    sortString: 'Spain',
    name: 'Vimusica – Musica y Video, S.l.',
    address1: 'C/ Mártires Concepcionistas,7 y 9 - B D',
    address2: '28006 Madrid',
    address3: 'Spain',
    agentName: 'Antonio Manuel dos Reis',
    phone: '+34 914023214',
    fax: '+34 914023642',
    email: 'vimusica@vimusica.com',
    url: 'http://www.vimusica.com/Login.aspx',
    urlDisplay: 'www.vimusica.com',
    sonicUrl: 'http://www.vimusica.com/Login.aspx',
  },
  {
    id: 19,
    country: 'United Arab Emirates',
    shortCountry: 'United Arab Emirates',
    sortString: 'United Arab Emirates',
    name: 'Big Bang & Fuzz Pty',
    address1: 'Suite 902 / 2-14 Kings Cross Road',
    address2: 'Potts Point NSW 2011',
    address3: 'Australia',
    agentName: 'Andrew Jones',
    phone: '+61 2 9326 9122',
    fax: '+61 2 9326 9166',
    email: 'music@bigbangfuzz.com',
    url: 'https://www.bigbangfuzz.com/',
    urlDisplay: 'www.bigbangfuzz.com',
    sonicUrl: 'https://www.bigbangfuzz.com/#/label/07f5949bd17cf38b',
  },
  {
    id: 20,
    country: 'Australia',
    shortCountry: 'Australia',
    sortString: 'Australia',
    name: 'Big Bang & Fuzz',
    address1: 'Suite 902 / 2-14 Kings Cross Road',
    address2: 'Potts Point NSW 2011',
    address3: 'Australia',
    agentName: 'Andrew Jones',
    phone: '+61 2 9326 9122',
    fax: '+61 2 9326 9166',
    email: 'music@bigbangfuzz.com',
    url: 'https://www.bigbangfuzz.com/',
    urlDisplay: 'www.bigbangfuzz.com',
    sonicUrl: 'https://www.bigbangfuzz.com/#/label/07f5949bd17cf38b',
  },
  {
    id: 21,
    country: 'Baltic States',
    shortCountry: 'Baltic States',
    sortString: 'Baltic States',
    name: 'Upright Music Scandinavia',
    address1: 'Vesterbrogade 74, 4',
    address2: 'DK-1620 Copenhagen',
    address3: 'Denmark',
    agentName: 'Jeppe Kaltoft',
    phone: '(+45) 70 26 14 00',
    fax: '',
    email: 'jk@upright-music.com',
    url: 'https://www.upright-music.com/',
    urlDisplay: 'www.upright-music.com',
    sonicUrl: 'https://search.upright-music.com/search/nojs?phrase[1]=sonic%20quiver',
  },
  {
    id: 22,
    country: 'Canada',
    shortCountry: 'Canada',
    sortString: 'Canada',
    name: 'ole clear',
    address1: '266 King Street West, Ste 500',
    address2: 'Toronto, M5V 1H8',
    address3: 'Canada',
    agentName: 'Steve Smith',
    phone: '855-814-5404',
    fax: '416-850-1173',
    email: 'steve_smith@oleclear.com',
    url: 'https://www.olemusicbox.com/',
    urlDisplay: 'www.olemusicbox.com',
    sonicUrl: 'http://public.olemusicbox.com/main/?searchtext=Library[sonic%20quiver]&0',
  },
  {
    id: 23,
    country: 'Denmark',
    shortCountry: 'Denmark',
    sortString: 'Denmark',
    name: 'Upright Music Scandinavia',
    address1: 'Vesterbrogade 74, 4',
    address2: 'DK-1620 Copenhagen',
    address3: 'Denmark',
    agentName: 'Jeppe Kaltoft',
    phone: '(+45) 70 26 14 00',
    fax: '',
    email: 'jk@upright-music.com',
    url: 'https://www.upright-music.com/',
    urlDisplay: 'www.upright-music.com',
    sonicUrl: 'https://search.upright-music.com/search/nojs?phrase[1]=sonic%20quiver',
  },
  {
    id: 24,
    country: 'France',
    shortCountry: 'France',
    sortString: 'France',
    name: 'Justement Music/Lido-Melodies',
    address1: '21/23 rue Carnot',
    address2: 'Montmorency, 95160',
    address3: 'France',
    agentName: 'Sébastien Bonneau',
    phone: '01 34 12 09 90',
    fax: '01 34 12 09 07',
    email: 'sebastien@justement-music.com',
    url: 'https://myma.emipm.com/en/',
    urlDisplay: 'www.justement-music.com',
    sonicUrl: 'https://myma.emipm.com/en/browse/labels/SQ',
  },
  {
    id: 25,
    country: 'Greece',
    shortCountry: 'Greece',
    sortString: 'Greece',
    name: 'Media Music Publishing',
    address1: '8 Zinonos Eleatou Str, 3rd floor',
    address2: '151 23 Maroussi',
    address3: 'Athens-Greece',
    agentName: 'Nikos Ghinis',
    phone: '0030 210 3600 569',
    fax: '003 210 3614 914',
    email: 'mediamusicpublishing@gmail.com',
    url: 'http://www.mediamusic.gr/',
    urlDisplay: 'www.mediamusic.gr',
    sonicUrl: 'http://www.mediamusic.gr//musStructures/byLabel/152',
  },
  {
    id: 26,
    country: 'Iceland',
    shortCountry: 'Iceland',
    sortString: 'Iceland',
    name: 'Upright Music Scandinavia',
    address1: 'Vesterbrogade 74, 4',
    address2: 'DK-1620 Copenhagen',
    address3: 'Denmark',
    agentName: 'Jeppe Kaltoft',
    phone: '(+45) 70 26 14 00',
    fax: '',
    email: 'jk@upright-music.com',
    url: 'https://www.upright-music.com/',
    urlDisplay: 'www.upright-music.com',
    sonicUrl: 'https://search.upright-music.com/search/nojs?phrase[1]=sonic%20quiver',
  },
  {
    id: 27,
    country: 'Ireland',
    shortCountry: 'Ireland',
    sortString: 'Ireland',
    name: 'Cavendish Music',
    address1: '4th Floor, Derbyshire House, St Chads Street',
    address2: 'London, WC1H 8AG',
    address3: 'United Kingdom',
    agentName: 'Gareth Owen',
    phone: '+44 207 054 7275',
    fax: '',
    email: 'gareth.owen@cavendishmusic.com',
    url: 'http://www.cavendishmusic.com/',
    urlDisplay: 'www.cavendishmusic.com',
    sonicUrl: 'https://search.cavendishmusic.com/home',
  },
  {
    id: 28,
    country: 'Italy',
    shortCountry: 'Italy',
    sortString: 'Italy',
    name: 'Flipper Srl',
    address1: 'Piazza Prati Strozzi 31',
    address2: 'Rome 195',
    address3: 'Italy',
    agentName: 'Fabio Di Bari',
    phone: '39 06 3722138',
    fax: '39 06 3722209',
    email: 'fabio@primrosemusic.com',
    url: 'https://www.flippermusic.it/',
    urlDisplay: 'www.flippermusic.it',
    sonicUrl: 'https://www.flippermusic.it/catalogo/3/sonic-quiver',
  },
  {
    id: 29,
    country: 'Latin America (except Mexico)',
    shortCountry: 'Latin America (except Mexico)',
    sortString: 'Latin America',
    name: 'Latin Music Publishing, Inc.',
    address1: '639 E Ocean Ave, Suite 405',
    address2: 'Boynton Beach, FL 33435',
    address3: 'USA',
    agentName: 'Peter Van Es',
    phone: '(561) 284-6118',
    fax: '',
    email: 'info@latinmusicpub.com',
    url: 'https://www.flippermusic.it/',
    urlDisplay: 'www.flippermusic.it',
    sonicUrl: 'https://www.musicdirectorla.com/labels/2681?sort=newest',
  },
  {
    id: 30,
    country: 'Malaysia',
    shortCountry: 'Malaysia',
    sortString: 'Malaysia',
    name: 'Big Bang & Fuzz',
    address1: 'Suite 902 / 2-14 Kings Cross Road',
    address2: 'Potts Point NSW 2011',
    address3: 'Australia',
    agentName: 'Andrew Jones',
    phone: '+61 2 9326 9122',
    fax: '+61 2 9326 9166',
    email: 'music@bigbangfuzz.com',
    url: 'https://www.bigbangfuzz.com/',
    urlDisplay: 'www.bigbangfuzz.com',
    sonicUrl: 'https://www.bigbangfuzz.com/#/label/07f5949bd17cf38b',
  },
  {
    id: 31,
    country: 'Netherlands',
    shortCountry: 'Netherlands',
    sortString: 'Netherlands',
    name: 'MusicDIRECTOR BV Publishing & Licensing',
    address1: 'Sumatralaan 45 (gebouw De Matrix)',
    address2: '1217 GP HILVERSUM',
    address3: 'Netherlands',
    agentName: 'Paul Gulmans',
    phone: '+31 (0)35 - 760 14 80',
    fax: '',
    email: 'paul@musicdirector.nl',
    url: 'https://bmgproductionmusic.nl/',
    urlDisplay: 'www.musicdirector.nl',
    sonicUrl: 'https://bmgproductionmusic.nl/labels/2681?sort=newest',
  },
  {
    id: 32,
    country: 'Norway',
    shortCountry: 'Norway',
    sortString: 'Norway',
    name: 'Upright Music Scandinavia',
    address1: 'Vesterbrogade 74, 4',
    address2: 'DK-1620 Copenhagen',
    address3: 'Denmark',
    agentName: 'Jeppe Kaltoft',
    phone: '(+45) 70 26 14 00',
    fax: '',
    email: 'jk@upright-music.com',
    url: 'https://www.upright-music.com/',
    urlDisplay: 'www.upright-music.com',
    sonicUrl: 'https://search.upright-music.com/search/nojs?phrase[1]=sonic%20quiver',
  },
  {
    id: 33,
    country: 'Portugal',
    shortCountry: 'Portugal',
    sortString: 'Portugal',
    name: 'Vimusica - Musica e Video, Lda.',
    address1: 'Av. Barbosa du Bocage, 23 - 1 D',
    address2: '1000-070 Lisboa',
    address3: 'Portugal',
    agentName: 'Elvira Gomes Reis',
    phone: '+351 217956195',
    fax: '+351 217973817',
    email: 'vimusica@vimusica.com',
    url: 'http://www.vimusica.com/Login.aspx',
    urlDisplay: 'www.vimusica.com',
    sonicUrl: 'http://www.vimusica.com/Login.aspx',
  },
  {
    id: 34,
    country: 'Romania',
    shortCountry: 'Romania',
    sortString: 'Romania',
    name: 'Blue Island Productions',
    address1: '300, Pantelimon St',
    address2: '8th floor, 2nd district',
    address3: 'Bucharest, Romania',
    agentName: 'Horea Pascu',
    phone: '+40 742 204 252',
    fax: '',
    email: 'horea@blueisland.ro',
    url: 'http://www.blueisland.ro/',
    urlDisplay: 'www.blueisland.ro',
    sonicUrl: 'http://www.blueisland.ro/librarie-sonic-quiver.php',
  },
  {
    id: 35,
    country: 'Slovakia',
    shortCountry: 'Slovakia',
    sortString: 'Slovakia',
    name: 'Studio Fontana spol. s r.o.',
    address1: 'V PodvrÅ¡Ã­ 1',
    address2: '182 00 Praha 8',
    address3: 'Czech Republic',
    agentName: 'ZdenÄ›k NedvÄ›d',
    phone: '+420 266 711 432-33',
    fax: '+420 266 711 432-33',
    email: 'library@studiofontana.com',
    url: 'http://www.studiofontana.com/',
    urlDisplay: 'www.studiofontana.com',
    sonicUrl: 'http://www.studiofontana.com/',
  },
  {
    id: 36,
    country: 'South Korea',
    shortCountry: 'South Korea',
    sortString: 'South Korea',
    name: 'Hi Five',
    address1: '4F Mok Cheon Bldg., 366-30',
    address2: 'Seogyo-dong, Mapo-gu,',
    address3: 'Seoul, South Korea',
    agentName: 'Grace Sky Lee',
    phone: '+82 (0)2 323 4667',
    fax: '+82 (0)2 323 4650',
    email: 'skylee@hi-finve.kr',
    url: 'http://www.hi-five.kr/',
    urlDisplay: 'www.hi-five.kr',
    sonicUrl: 'http://www.hi-five.kr/',
  },
  {
    id: 37,
    country: 'Sweden',
    shortCountry: 'Sweden',
    sortString: 'Sweden',
    name: 'Upright Music Scandinavia',
    address1: 'Vesterbrogade 74, 4',
    address2: 'DK-1620 Copenhagen',
    address3: 'Denmark',
    agentName: 'Jeppe Kaltoft',
    phone: '(+45) 70 26 14 00',
    fax: '',
    email: 'jk@upright-music.com',
    url: 'https://www.upright-music.com/',
    urlDisplay: 'www.upright-music.com',
    sonicUrl: 'https://search.upright-music.com/search/nojs?phrase[1]=sonic%20quiver',
  },
  {
    id: 38,
    country: 'Thailand',
    shortCountry: 'Thailand',
    sortString: 'Thailand',
    name: 'Big Bang & Fuzz',
    address1: 'Suite 902 / 2-14 Kings Cross Road',
    address2: 'Potts Point NSW 2011',
    address3: 'Australia',
    agentName: 'Andrew Jones',
    phone: '+61 2 9326 9122',
    fax: '+61 2 9326 9166',
    email: 'music@bigbangfuzz.com',
    url: 'https://www.bigbangfuzz.com/',
    urlDisplay: 'www.bigbangfuzz.com',
    sonicUrl: 'https://www.bigbangfuzz.com/#/label/07f5949bd17cf38b',
  },
  {
    id: 39,
    country: 'United Kingdom',
    shortCountry: 'United Kingdom',
    sortString: 'United Kingdom',
    name: 'Cavendish Music',
    address1: '4th Floor, Derbyshire House, St Chads Street',
    address2: 'London, WC1H 8AG',
    address3: 'United Kingdom',
    agentName: 'Gareth Owen',
    phone: '+44 207 054 7275',
    fax: '',
    email: 'gareth.owen@cavendishmusic.com',
    url: 'http://www.cavendishmusic.com/',
    urlDisplay: 'www.cavendishmusic.com',
    sonicUrl: 'https://search.cavendishmusic.com/home',
  },
]
